import Head from 'next/head'
import Contact from './Contact'
import Footer from './Footer'
import Navbar from './Navbar'

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Billy Bee Kids Fishing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="justify-center items-center">
        <div className="container mx-auto">{children}</div>
      </div>
      <Contact/>
      <Footer />
    </>
  )
}

export default Layout
